POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "user",
    "password": "user",
    "email": "user@gmail.com"
}


####
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "user",
    "password": "user"
}


####
GET http://localhost:3001/api/products/1111 
content-type: application/json

